unique_ids:
  assets:
    standard-page.html: VLAUAMW2P4WZVHGR3FS57WUF4VQ6BIH3
    theme.css: QF4BKVS5VVPBALY52EDACP3DQ4I2PYRP
  forms:
    Form1: XYRTXS6OHJATBTP7YBYQBFZYN5T7FNNV
  modules: {}
  scripts: {}
  server_modules:
    DataBase: '1732703233267402822892032.65796'
